# Generated by Django 5.2.14 on 2026-05-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'especialidade',
                'verbose_name_plural': 'especialidades',
                'ordering': ['nome'],
            },
        ),
    ]
