# Generated by Django 5.2.14 on 2026-05-08 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autor', '0001_initial'),
        ('categoria', '0001_initial'),
        ('especialidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, default='')),
                ('link', models.URLField(blank=True, default='', max_length=500)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='autor.autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='categoria.categoria')),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='especialidade.especialidade')),
            ],
            options={
                'verbose_name': 'conteúdo',
                'verbose_name_plural': 'conteúdos',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
