# Generated by Django 5.2.14 on 2026-05-22 22:26

import server_medic.conteudo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=server_medic.conteudo.models.conteudo_upload_path),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='corpo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
