# Generated by Django 5.2.14 on 2026-05-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_plataforma', models.CharField(max_length=150)),
                ('crm', models.CharField(max_length=50)),
                ('atuacao', models.CharField(max_length=200)),
                ('instituicao', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'autor',
                'verbose_name_plural': 'autores',
            },
        ),
    ]
